/*
 * This file has been automatically generated by the jrl-cmakemodules.
 * Please see https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/config.hh.cmake for details.
*/

#ifndef ODRI_CONTROL_INTERFACE_CONFIG_HH
# define ODRI_CONTROL_INTERFACE_CONFIG_HH

// Package version (header).
# define ODRI_CONTROL_INTERFACE_VERSION_UNKNOWN_TAG 0 // Used to mention that the current version is unknown.
# define ODRI_CONTROL_INTERFACE_VERSION "1.0.1"
# define ODRI_CONTROL_INTERFACE_MAJOR_VERSION 1
# define ODRI_CONTROL_INTERFACE_MINOR_VERSION 0
# define ODRI_CONTROL_INTERFACE_PATCH_VERSION 1

#define ODRI_CONTROL_INTERFACE_VERSION_AT_LEAST(major, minor, patch) (ODRI_CONTROL_INTERFACE_MAJOR_VERSION>major || (ODRI_CONTROL_INTERFACE_MAJOR_VERSION>=major && \
                                                             (ODRI_CONTROL_INTERFACE_MINOR_VERSION>minor || (ODRI_CONTROL_INTERFACE_MINOR_VERSION>=minor && \
                                                                                                     ODRI_CONTROL_INTERFACE_PATCH_VERSION>=patch))))

#define ODRI_CONTROL_INTERFACE_VERSION_AT_MOST(major, minor, patch) (ODRI_CONTROL_INTERFACE_MAJOR_VERSION<major || (ODRI_CONTROL_INTERFACE_MAJOR_VERSION<=major && \
                                                            (ODRI_CONTROL_INTERFACE_MINOR_VERSION<minor || (ODRI_CONTROL_INTERFACE_MINOR_VERSION<=minor && \
                                                                                                     ODRI_CONTROL_INTERFACE_PATCH_VERSION<=patch))))

// Handle portable symbol export.
// Defining manually which symbol should be exported is required
// under Windows whether MinGW or MSVC is used.
//
// The headers then have to be able to work in two different modes:
// - dllexport when one is building the library,
// - dllimport for clients using the library.
//
// On Linux, set the visibility accordingly. If C++ symbol visibility
// is handled by the compiler, see: http://gcc.gnu.org/wiki/Visibility
//
// Explicit template instantiation on Windows need to add
// dllexport on the definition and dllimport on the declaration.
// The XXX_EXPLICIT_INSTANTIATION_DECLARATION_DLLAPI macro
// should be set on the declaration while
// the XXX_EXPLICIT_INSTANTIATION_DEFINITION_DLLAPI macro
// should be set on the definition.
# if defined _WIN32 || defined __CYGWIN__
// On Microsoft Windows, use dllimport and dllexport to tag symbols.
#  define ODRI_CONTROL_INTERFACE_DLLIMPORT __declspec(dllimport)
#  define ODRI_CONTROL_INTERFACE_DLLEXPORT __declspec(dllexport)
#  define ODRI_CONTROL_INTERFACE_DLLLOCAL
#  define ODRI_CONTROL_INTERFACE_EXPLICIT_INSTANTIATION_DECLARATION_DLLIMPORT __declspec(dllimport)
#  define ODRI_CONTROL_INTERFACE_EXPLICIT_INSTANTIATION_DECLARATION_DLLEXPORT
#  define ODRI_CONTROL_INTERFACE_EXPLICIT_INSTANTIATION_DEFINITION_DLLIMPORT __declspec(dllimport)
#  define ODRI_CONTROL_INTERFACE_EXPLICIT_INSTANTIATION_DEFINITION_DLLEXPORT __declspec(dllexport)
# else
// On Linux, for GCC >= 4, tag symbols using GCC extension.
#  if __GNUC__ >= 4
#   define ODRI_CONTROL_INTERFACE_DLLIMPORT __attribute__ ((visibility("default")))
#   define ODRI_CONTROL_INTERFACE_DLLEXPORT __attribute__ ((visibility("default")))
#   define ODRI_CONTROL_INTERFACE_DLLLOCAL  __attribute__ ((visibility("hidden")))
#   define ODRI_CONTROL_INTERFACE_EXPLICIT_INSTANTIATION_DECLARATION_DLLIMPORT __attribute__ ((visibility("default")))
#   define ODRI_CONTROL_INTERFACE_EXPLICIT_INSTANTIATION_DECLARATION_DLLEXPORT __attribute__ ((visibility("default")))
#   define ODRI_CONTROL_INTERFACE_EXPLICIT_INSTANTIATION_DEFINITION_DLLIMPORT
#   define ODRI_CONTROL_INTERFACE_EXPLICIT_INSTANTIATION_DEFINITION_DLLEXPORT
#  else
// Otherwise (GCC < 4 or another compiler is used), export everything.
#   define ODRI_CONTROL_INTERFACE_DLLIMPORT
#   define ODRI_CONTROL_INTERFACE_DLLEXPORT
#   define ODRI_CONTROL_INTERFACE_DLLLOCAL
#   define ODRI_CONTROL_INTERFACE_EXPLICIT_INSTANTIATION_DECLARATION_DLLIMPORT
#   define ODRI_CONTROL_INTERFACE_EXPLICIT_INSTANTIATION_DECLARATION_DLLEXPORT
#   define ODRI_CONTROL_INTERFACE_EXPLICIT_INSTANTIATION_DEFINITION_DLLIMPORT
#   define ODRI_CONTROL_INTERFACE_EXPLICIT_INSTANTIATION_DEFINITION_DLLEXPORT
#  endif // __GNUC__ >= 4
# endif // defined _WIN32 || defined __CYGWIN__

# ifdef ODRI_CONTROL_INTERFACE_STATIC
// If one is using the library statically, get rid of
// extra information and use standard explicit template
// instantiation keyword.
#  define ODRI_CONTROL_INTERFACE_DLLAPI
#  define ODRI_CONTROL_INTERFACE_LOCAL
#  define ODRI_CONTROL_INTERFACE_EXPLICIT_INSTANTIATION_DECLARATION extern template
# else
// Depending on whether one is building or using the
// library define DLLAPI to import or export and
// define the right explicit template instantiation keyword.
#  ifdef odri_control_interface_EXPORTS
#   define ODRI_CONTROL_INTERFACE_DLLAPI ODRI_CONTROL_INTERFACE_DLLEXPORT
#   define ODRI_CONTROL_INTERFACE_EXPLICIT_INSTANTIATION_DECLARATION_DLLAPI ODRI_CONTROL_INTERFACE_EXPLICIT_INSTANTIATION_DECLARATION_DLLEXPORT
#   define ODRI_CONTROL_INTERFACE_EXPLICIT_INSTANTIATION_DEFINITION_DLLAPI ODRI_CONTROL_INTERFACE_EXPLICIT_INSTANTIATION_DEFINITION_DLLEXPORT
#  else
#   define ODRI_CONTROL_INTERFACE_DLLAPI ODRI_CONTROL_INTERFACE_DLLIMPORT
#   define ODRI_CONTROL_INTERFACE_EXPLICIT_INSTANTIATION_DECLARATION_DLLAPI ODRI_CONTROL_INTERFACE_EXPLICIT_INSTANTIATION_DECLARATION_DLLIMPORT
#   define ODRI_CONTROL_INTERFACE_EXPLICIT_INSTANTIATION_DEFINITION_DLLAPI ODRI_CONTROL_INTERFACE_EXPLICIT_INSTANTIATION_DEFINITION_DLLIMPORT
#  endif // ODRI_CONTROL_INTERFACE_EXPORTS
#  define ODRI_CONTROL_INTERFACE_LOCAL ODRI_CONTROL_INTERFACE_DLLLOCAL
# endif // ODRI_CONTROL_INTERFACE_STATIC
#endif //! ODRI_CONTROL_INTERFACE_CONFIG_HH
